name: marked_text
description: Interpret text by marking certain sections with specified tokens, allowing for custom callbacks and styling
version: 0.0.5
repository: https://github.com/tratteo/marked_text
issue_tracker: https://github.com/tratteo/marked_text/issues

platforms:
    android:
    ios:
    linux:
    macos:
    windows:

environment:
    sdk: ">=2.19.4 <4.0.0"
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter

    url_launcher: ^6.1.10

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1

flutter:
